### PR TITLE
Clean up code

### PR DESCRIPTION
**Pull request by wolfreak99**
Alot of the code faced inconsistencies and implied access to many functions and variables. It's always best to explicitly define the access modifier for clarity. If the other PR gets merged first, I can happily rebase this one to that.

### CODE REVIEW

**Comment by marijnz** [comment]
Hey, yes so another one got merged first, so there's just a couple conflicts to be resolved. Thanks for the PR! I agree with what you did. I'm generally in favour of not explicitly writing out private. However in another PR I said I'm going with whatever Unity does to keep it simple and consistent, and they do add it! So let's just do that 👍

**Comment by wolfreak99** [comment]
While aesthetically speaking, it does look more pleasing to not include private, But, the idea behind explicitly writing out private is to clarify to people who may not know c# and end up reading the code, that way any guesswork on their end is reduced. Different languages have different default access modifiers, and sometimes defaults change over time.  I'll resolve the conflicts in a moment!

**Comment by wolfreak99** [comment]
I was having issues rebasing this and I had to merge them all as a last resort,but everything is rebased and the formatting was added to the other code too

**Comment by wolfreak99** [comment]
I am finished with this, by the way.

**Comment by marijnz** [comment]
Sorry for late response, I'm currently travelling and had barely to no internet the last couple weeks, merging it! 👍

**Pull request merged**
